name: Build
on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
<<<<<<< HEAD
          flutter-version: "3.7.x" # you can use 1.7
          channel: "stable" # optional, default to: 'stable'
=======
          flutter-version: "2.5.x" # you can use 1.12
          channel: "stable" # Currently you have to use beta channel for Flutter web.
      - name: Upgrades Flutter
        run: flutter upgrade
        working-directory: ./example
>>>>>>> 0909b558a9c87a25925a050f8fb897166d4d8e81
      - run: flutter pub get
        working-directory: ./example
      - run: flutter build apk --debug
        working-directory: ./example
